name: "[Reusable workflows] push published entries"

on:
  workflow_call:
    secrets:
      OWNER_API_KEY:
        required: true

jobs:
  upload-images:
    if: github.event.pull_request.merged == false
    uses: hatena/hatenablog-workflows/.github/workflows/upload-images.yaml@1e932419b6749d6b4ad3d0e30d07df87a1ed3c3e # v1
    secrets:
      OWNER_API_KEY: ${{ secrets.OWNER_API_KEY }}
